export const DEMO_TILES = "DEMO_TILES";
export const NATURAL_EARTH_TILES = "NATURAL_EARTH_TILES";
export const OPENSTREETMAP = "OPENSTREETMAP";
export const ARCGIS = "ARCGIS";
export const EMODNET = "EMODNET";
export const USGS = "USGS";

export const HEXAGON = "HEXAGON";
export const HEATMAP_POINTS = "HEATMAP_POINTS";
export const HEATMAP_REGIONS = "HEATMAP_REGIONS";
export const NO_CLUSTER = "NO_CLUSTER";

export const REGIONS_SOURCE = "REGIONS_SOURCE";
export const REGIONS_LAYER = "REGIONS_LAYER";

export const POINTS_SOURCE = "POINTS_SOURCE";
export const POINTS_LAYER = "POINTS_LAYER";

export const HEXAGON_SOURCE = "HEXAGON_SOURCE";
export const HEXAGON_LAYER = "HEXAGON_LAYER";

export const HEATMAP_POINTS_SOURCE = "HEATMAP_POINTS_SOURCE";
export const HEATMAP_POINTS_LAYER = "HEATMAP_POINTS_LAYER";

export const HEATMAP_REGIONS_SOURCE = "HEATMAP_REGIONS_SOURCE";
export const HEATMAP_REGIONS_LAYER = "HEATMAP_REGIONS_LAYER";
