---
version: '3.7'

services:
    golden:
        image: fils/golden:latest
        container_name: golden
        ports:
            - 6789:6789


    t1:
        image: oxigraph/oxigraph
        container_name: triplestore
        ports:
            - 7878:7878
#        volumes:
#            - ./data/oxigraph:/data
