search_calcium_and_creative_work_response = {
    'response': {'numFound': 4, 'start': 0, 'numFoundExact': True, 'docs': [
         {'id': 'https://edmerp.seadatanet.org/report/7985', 'type': 'ResearchProject',
          'name': 'The impact of Coccolithophorid blooms off western Ireland', 'txt_identifier': ['7985'],
          'txt_alternateName': ['N/A'], 'txt_url': ['https://edmerp.seadatanet.org/report/7985'],
          'txt_sameAs': ['http://www.nuigalway.ie/microbiology/dr__john_w__patching.html'],
          'description': 'High concentrations or blooms of the coccolithophorid Emiliania huxleyi can significantly affect a region by acting as a source of organic sulfur (i.e. dimethyl sulfide) to the atmosphere and calcium carbonate to the sediments, and by altering the optical properties of the surface layer. Documenting the occurrence of blooms in time and space is therefore essential in characterizing the biogeochemical environment of a region. Furthermore, their distribution pattern can be employed to define the environmental conditions favorable for their occurrence. E. huxleyi blooms can be distinguished from most other conditions in visible satellite imagery by their milkly white to turquoise appearance. This project funded under the Environmental Change Institute aims to examine of these blooms off the west coast of Ireland.',
          'txt_areaServed': ['West Coordinate: -12 East Coordinate: -9 North Coordinate: 56 South Coordinate: 51'],
          'txt_parentOrganization': ['https://edmo.seadatanet.org/report/774'],
          'txt_memberOf': ['European Directory of Marine Environmental Research Projects (EDMERP)',
                           'https://edmo.seadatanet.org/report/774'],
          'keys': ['id', 'type', 'name', 'txt_identifier', 'txt_alternateName', 'txt_url', 'txt_sameAs', 'description',
                   'txt_areaServed', 'txt_parentOrganization', 'txt_memberOf'],
          'json_source': '{"@context": {"@vocab": "https://schema.org/"}, "@type": "ResearchProject", "@id": "https://edmerp.seadatanet.org/report/7985", "name": "The impact of Coccolithophorid blooms off western Ireland", "identifier": "7985", "alternateName": "N/A", "url": "https://edmerp.seadatanet.org/report/7985", "sameAs": "http://www.nuigalway.ie/microbiology/dr__john_w__patching.html", "description": "High concentrations or blooms of the coccolithophorid Emiliania huxleyi can significantly affect a region by acting as a source of organic sulfur (i.e. dimethyl sulfide) to the atmosphere and calcium carbonate to the sediments, and by altering the optical properties of the surface layer. Documenting the occurrence of blooms in time and space is therefore essential in characterizing the biogeochemical environment of a region. Furthermore, their distribution pattern can be employed to define the environmental conditions favorable for their occurrence. E. huxleyi blooms can be distinguished from most other conditions in visible satellite imagery by their milkly white to turquoise appearance. This project funded under the Environmental Change Institute aims to examine of these blooms off the west coast of Ireland.", "areaServed": "West Coordinate: -12 East Coordinate: -9 North Coordinate: 56 South Coordinate: 51", "parentOrganization": {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/774"}, "memberOf": [{"@type": "ProgramMembership", "programName": "European Directory of Marine Environmental Research Projects (EDMERP)"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/774"}]}',
          'index_id': '8c9e2611-7976-4267-bad4-1308714aec6e', '_version_': '1726272489341845504',
          'indexed_ts': '2022-03-03T10:02:16.204Z'},
         {'id': 'https://edmerp.seadatanet.org/report/12053', 'type': 'ResearchProject',
          'name': 'Geodynamical map of the Polish coastal zone 1:10,000', 'txt_identifier': ['12053'],
          'txt_url': ['https://edmerp.seadatanet.org/report/12053'],
          'description': 'During 1985-2006, ca 500 km of echosounding profiles were carried out and ca 1000 km of shallow seismic lines, cores (210 m) and boreholes (640 m) in the sea, cores (4300 m) and manual drillings (2000 m) on the beach, ca 1400 morphometric profiles, 357 profiles of cliffs, 374 profiles of dunes, 82 hollows were made. Standard investigations in the laboratory were done including: 2346 analyses of grain size distributions, 714 content of heavy minerals, 135 composition of heavy minerals and 846 analyses of calcium carbonate. Also, 14C, TL, pollen, diatomological micro- and macrofauna analyses were carried out. The results of cruises and laboratory work are presented on 65 sheets of geodynamical maps (scale 1:10,000). The results of cruises and laboratory work are also stored in a computer database (Fox-Pro). Only echograms and shallow seismic are recorded in the CODA acquisition system.',
          'txt_areaServed': [
              'A strip along the Polish coastline, 2.5 km width (1 km on the land side and 1.5 km on the sea side), including the Puck Lagoon'],
          'txt_parentOrganization': ['https://edmo.seadatanet.org/report/609'],
          'txt_memberOf': ['European Directory of Marine Environmental Research Projects (EDMERP)',
                           'https://edmo.seadatanet.org/report/609'],
          'keys': ['id', 'type', 'name', 'txt_identifier', 'txt_url', 'description', 'txt_areaServed',
                   'txt_parentOrganization', 'txt_memberOf'],
          'json_source': '{"@context": {"@vocab": "https://schema.org/"}, "@type": "ResearchProject", "@id": "https://edmerp.seadatanet.org/report/12053", "name": "Geodynamical map of the Polish coastal zone 1:10,000", "identifier": "12053", "url": "https://edmerp.seadatanet.org/report/12053", "description": "During 1985-2006, ca 500 km of echosounding profiles were carried out and ca 1000 km of shallow seismic lines, cores (210 m) and boreholes (640 m) in the sea, cores (4300 m) and manual drillings (2000 m) on the beach, ca 1400 morphometric profiles, 357 profiles of cliffs, 374 profiles of dunes, 82 hollows were made. Standard investigations in the laboratory were done including: 2346 analyses of grain size distributions, 714 content of heavy minerals, 135 composition of heavy minerals and 846 analyses of calcium carbonate. Also, 14C, TL, pollen, diatomological micro- and macrofauna analyses were carried out. The results of cruises and laboratory work are presented on 65 sheets of geodynamical maps (scale 1:10,000). The results of cruises and laboratory work are also stored in a computer database (Fox-Pro). Only echograms and shallow seismic are recorded in the CODA acquisition system.", "areaServed": "A strip along the Polish coastline, 2.5 km width (1 km on the land side and 1.5 km on the sea side), including the Puck Lagoon", "parentOrganization": {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/609"}, "memberOf": [{"@type": "ProgramMembership", "programName": "European Directory of Marine Environmental Research Projects (EDMERP)"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/609"}]}',
          'index_id': '1b7d8bf9-ffb1-481d-b30d-b0437264da1a', '_version_': '1726272485899370496',
          'indexed_ts': '2022-03-03T10:02:12.921Z'},
         {'id': 'https://edmerp.seadatanet.org/report/12283', 'type': 'ResearchProject',
          'name': 'The accidification of the sea', 'txt_identifier': ['12283'], 'txt_alternateName': ['Havets forsurnin'],
          'txt_url': ['https://edmerp.seadatanet.org/report/12283'], 'txt_sameAs': ['http://www.smhi.se/havetsforsurning'],
          'description': 'Over the past century the garden has raised about 40% of the human produced carbon dioxide derived from fossil fuels. This has meant that the carbon dioxide content in the garden has increased. When the garden absorbs carbon dioxide, the pH drops and in the Baltic Sea and the North Sea, a decrease in pH has been observed in recent decades. A change in acidity and saturation of calcium carbonate results in changes in both chemical and biological processes. The impact on the marine ecosystem is to be expected and studies on marine organisms show that serious effects are likely within a hundred years. the purpose of the project The state of the carbonate system in the garden around Sweden is not well known. The project aims at examining the state of the Baltic Sea and the North Sea carbonate system by measurements of pCO2 and pH with high resolution in time and space.',
          'txt_areaServed': ['From the Bothnian Bay , in to the Finnish Bay and southward through the Baltic Sea.'],
          'txt_parentOrganization': ['https://edmo.seadatanet.org/report/545'],
          'txt_memberOf': ['European Directory of Marine Environmental Research Projects (EDMERP)',
                           'https://edmo.seadatanet.org/report/1334', 'https://edmo.seadatanet.org/report/1353',
                           'https://edmo.seadatanet.org/report/3512', 'https://edmo.seadatanet.org/report/545'],
          'keys': ['id', 'type', 'name', 'txt_identifier', 'txt_alternateName', 'txt_url', 'txt_sameAs', 'description',
                   'txt_areaServed', 'txt_parentOrganization', 'txt_memberOf'],
          'json_source': '{"@context": {"@vocab": "https://schema.org/"}, "@type": "ResearchProject", "@id": "https://edmerp.seadatanet.org/report/12283", "name": "The accidification of the sea", "identifier": "12283", "alternateName": "Havets forsurnin", "url": "https://edmerp.seadatanet.org/report/12283", "sameAs": "http://www.smhi.se/havetsforsurning", "description": "Over the past century the garden has raised about 40% of the human produced carbon dioxide derived from fossil fuels. This has meant that the carbon dioxide content in the garden has increased. When the garden absorbs carbon dioxide, the pH drops and in the Baltic Sea and the North Sea, a decrease in pH has been observed in recent decades. A change in acidity and saturation of calcium carbonate results in changes in both chemical and biological processes. The impact on the marine ecosystem is to be expected and studies on marine organisms show that serious effects are likely within a hundred years. the purpose of the project The state of the carbonate system in the garden around Sweden is not well known. The project aims at examining the state of the Baltic Sea and the North Sea carbonate system by measurements of pCO2 and pH with high resolution in time and space.", "areaServed": "From the Bothnian Bay , in to the Finnish Bay and southward through the Baltic Sea.", "parentOrganization": {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/545"}, "memberOf": [{"@type": "ProgramMembership", "programName": "European Directory of Marine Environmental Research Projects (EDMERP)"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/545"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/1353"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/3512"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/1334"}]}',
          'index_id': '959b1481-e120-47db-9117-5c31a0499afc', '_version_': '1726270526919278592',
          'indexed_ts': '2022-03-03T09:31:04.692Z'},
         {'id': 'https://edmerp.seadatanet.org/report/3545', 'type': 'ResearchProject',
      'name': 'Role of oceanic production and dissolution of calcium carbonate in climate change',
      'txt_identifier': ['3545'], 'txt_alternateName': ['CCCC ULB-LOCGE'],
      'txt_url': ['https://edmerp.seadatanet.org/report/3545'],
      'description': "The overall objective of this research project is to gain a better knowledge of the oceanic inorganic carbon cycle and its role in climate change. With the combination of field investigations, laboratory experiments and modelling efforts, we aim to study the processes associated with the oceanic production and dissolution of calcium carbonate in order to quantify the role of calcifying phytoplanktonic organisms in sequestering CO2. Our field studies will be carried out in the area of La Chapelle Bank area (about 47 30'N, 7 30'W) in the Gulf of Biscay. Field investigations, supported by remote sensing data, will provide basic, physical, chemical (nutrients, carbon organic and inorganic species), biological (phytoplankton and zooplankton) information. Suspended matter will be collected by continuous centrifugation, in situ filtration of large volumes of water and short-term deployments of sediment traps. In addition, process-oriented studies of the production of organic and inorganic particulate carbon and the dissolution of calcium carbonate will be conducted, using 14C incorporation experiments. The influence of zooplankton grazing and of microbial degradation of organic matter on the dissolution of CaCO3 will be investigated in detail. The co-ordinator, the Laboratory of Chemical Oceanography and Water Geochemistry at the University of Brussels (ULB-LOCGE), is responsible for quantifying the production of organic and inorganic carbon and for studying the dissolution mechanisms of biogenic CaCO3 related to microbial respiration.",
      'txt_areaServed': ['La Chapelle Bank area, Gulf of Biscay'],
      'txt_parentOrganization': ['https://edmo.seadatanet.org/report/240'],
      'txt_memberOf': ['European Directory of Marine Environmental Research Projects (EDMERP)',
                       'https://edmo.seadatanet.org/report/199', 'https://edmo.seadatanet.org/report/240',
                       'https://edmo.seadatanet.org/report/438'],
      'keys': ['id', 'type', 'name', 'txt_identifier', 'txt_alternateName', 'txt_url', 'description', 'txt_areaServed',
               'txt_parentOrganization', 'txt_memberOf'],
      'json_source': '{"@context": {"@vocab": "https://schema.org/"}, "@type": "ResearchProject", "@id": "https://edmerp.seadatanet.org/report/3545", "name": "Role of oceanic production and dissolution of calcium carbonate in climate change", "identifier": "3545", "alternateName": "CCCC ULB-LOCGE", "url": "https://edmerp.seadatanet.org/report/3545", "description": "The overall objective of this research project is to gain a better knowledge of the oceanic inorganic carbon cycle and its role in climate change. With the combination of field investigations, laboratory experiments and modelling efforts, we aim to study the processes associated with the oceanic production and dissolution of calcium carbonate in order to quantify the role of calcifying phytoplanktonic organisms in sequestering CO2. Our field studies will be carried out in the area of La Chapelle Bank area (about 47 30\'N, 7 30\'W) in the Gulf of Biscay. Field investigations, supported by remote sensing data, will provide basic, physical, chemical (nutrients, carbon organic and inorganic species), biological (phytoplankton and zooplankton) information. Suspended matter will be collected by continuous centrifugation, in situ filtration of large volumes of water and short-term deployments of sediment traps. In addition, process-oriented studies of the production of organic and inorganic particulate carbon and the dissolution of calcium carbonate will be conducted, using 14C incorporation experiments. The influence of zooplankton grazing and of microbial degradation of organic matter on the dissolution of CaCO3 will be investigated in detail. The co-ordinator, the Laboratory of Chemical Oceanography and Water Geochemistry at the University of Brussels (ULB-LOCGE), is responsible for quantifying the production of organic and inorganic carbon and for studying the dissolution mechanisms of biogenic CaCO3 related to microbial respiration.", "areaServed": "La Chapelle Bank area, Gulf of Biscay", "parentOrganization": {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/240"}, "memberOf": [{"@type": "ProgramMembership", "programName": "European Directory of Marine Environmental Research Projects (EDMERP)"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/240"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/199"}, {"@type": "Organization", "url": "https://edmo.seadatanet.org/report/438"}]}',
      'index_id': 'a12be569-bd27-418b-9a6b-af30e23f21c7', '_version_': '1726270436564533248',
      'indexed_ts': '2022-03-03T09:29:38.522Z'}]},
    'facet_counts': {
        'facet_queries': {},
        'facet_fields': {'txt_knowsAbout': [], 'name': [
            'Geodynamical map of the Polish coastal zone 1:10,000',
            1,
            'Role of oceanic production and dissolution of calcium carbonate in climate change',
            1, 'The accidification of the sea', 1,
            'The impact of Coccolithophorid blooms off western Ireland',
            1], 'txt_knowsLanguage': [],
                         'txt_nationality': [],
                         'txt_jobTitle': [],
                         'txt_contributor': [],
                         'txt_keywords': [],
                         'txt_memberOf': [
                             'European Directory of Marine Environmental Research Projects (EDMERP)',
                             4,
                             'https://edmo.seadatanet.org/report/1334',
                             1,
                             'https://edmo.seadatanet.org/report/1353',
                             1,
                             'https://edmo.seadatanet.org/report/199',
                             1,
                             'https://edmo.seadatanet.org/report/240',
                             1,
                             'https://edmo.seadatanet.org/report/3512',
                             1,
                             'https://edmo.seadatanet.org/report/438',
                             1,
                             'https://edmo.seadatanet.org/report/545',
                             1,
                             'https://edmo.seadatanet.org/report/609',
                             1,
                             'https://edmo.seadatanet.org/report/774',
                             1], 'txt_parentOrganization': [
                'https://edmo.seadatanet.org/report/240', 1,
                'https://edmo.seadatanet.org/report/545', 1,
                'https://edmo.seadatanet.org/report/609', 1,
                'https://edmo.seadatanet.org/report/774',
                1], 'id_provider': [],
                         'id_includedInDataCatalog': [],
                         'id_identifier': [], 'id': [
                'https://edmerp.seadatanet.org/report/12053',
                1,
                'https://edmerp.seadatanet.org/report/12283',
                1,
                'https://edmerp.seadatanet.org/report/3545',
                1,
                'https://edmerp.seadatanet.org/report/7985',
                1], 'keys': ['description', 4, 'id', 4,
                             'name', 4, 'txt_areaServed', 4,
                             'txt_identifier', 4,
                             'txt_memberOf', 4,
                             'txt_parentOrganization', 4,
                             'txt_url', 4, 'type', 4,
                             'txt_alternateName', 3,
                             'txt_sameAs', 2],
                         'type': ['ResearchProject', 4]},
        'facet_ranges': {}, 'facet_intervals': {},
        'facet_heatmaps': {}}}
