# Backport action, driven by a pull request's LABEL name
#   if a pull request contains a label of "backport-branch-0-1", then
#   this action will backport that pull request to "branch-0-1"
# homepage: https://github.com/m-kuhn/backport

name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport Bot
        id: backport
        if: github.event.pull_request.merged && ( ( github.event.action == 'closed' && contains( join( github.event.pull_request.labels.*.name ), 'backport') ) || contains( github.event.label.name, 'backport' ) )        
        uses: m-kuhn/backport@v1.2.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
